# Generated by Django 2.2.9 on 2020-01-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_variants',
        ),
    ]
